port module Routes exposing (..)

-- Do not edit this file manually.

import Json.Decode exposing (Value)


port get : String -> Cmd msg


port post : Value -> Cmd msg


port patch : Value -> Cmd msg


port delete : String -> Cmd msg



login : String
login =
    "login"


logout : String
logout =
    "logout"


register : String
register =
    "register"


passwordRequest : String
passwordRequest =
    "password/reset"


passwordEmail : String
passwordEmail =
    "password/email"


passwordReset : String -> String
passwordReset token =
    "password/reset/{token}"
        |> String.replace "{token}" token


passwordUpdate : String
passwordUpdate =
    "password/reset"


verificationNotice : String
verificationNotice =
    "email/verify"


verificationVerify : String -> String -> String
verificationVerify id hash =
    "email/verify/{id}/{hash}"
        |> String.replace "{id}" id
        |> String.replace "{hash}" hash


verificationResend : String
verificationResend =
    "email/resend"


home : String
home =
    "home"


todos : String
todos =
    "todos"


todosStore : String
todosStore =
    "todos"


todosUpdate : String -> String
todosUpdate todo =
    "todos/{todo}"
        |> String.replace "{todo}" todo


todosDestroy : String -> String
todosDestroy todo =
    "todos/{todo}"
        |> String.replace "{todo}" todo


todosToggleAll : String
todosToggleAll =
    "todos/toggle-all"


todosClearCompleted : String
todosClearCompleted =
    "todos/clear-completed"


storageLocal : String -> String
storageLocal path =
    "storage/{path}"
        |> String.replace "{path}" path
